# https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  php:
    image: lehungio/php-fpm:7.4
    tty: true
    restart: always
    container_name: php-me-sample
    hostname: php-me-sample
    working_dir: /code
    volumes:
      - $PWD:/code
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build: .
    tty: true
    restart: always
    container_name: nginx-build
    hostname: nginx-build
    domainname: nginx.test
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - $PWD:/code
      - $PWD/docker/build/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/docker/build/nginx/config/blacklist.conf:/etc/nginx/blacklist.conf
      - $PWD/docker/build/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/docker/build/nginx/config/localhost.conf:/etc/nginx/conf.d/localhost.conf
      - $PWD/docker/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - default
    depends_on:
      - php
    # command: ["wait-for-it.sh", "sample_web1:80", "--", "./wait-for-it.sh", "sample_web2:80"]